[build]
  publish = "/"
  functions = "netlify/functions"

# Redirect /feed.xml to the function
[[redirects]]
  from = "/feed.xml"
  to = "/.netlify/functions/rss"
  status = 200

# Headers for the function endpoint
[[headers]]
  for = "/.netlify/functions/rss"
  [headers.values]
    Content-Type = "application/rss+xml; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Keep your existing headers as backup
[[headers]]
  for = "/feed.xml"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/rss+xml; charset=UTF-8"