name: Generate RSS Feed

on:
  schedule:
    - cron: '0 * * * *'   # runs every hour
  workflow_dispatch:       # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate RSS feed
      run: python generate_rss.py

    - name: Commit and push RSS feed updates
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add feed.xml

        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update RSS feed - $(date '+%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        fi
